language: Java

notifications:
  irc:
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    email:
      recipients:
        - hubert.lindenau@gmail.com
      on_success: never
      on_failure: always
    
